name: flutter_fft
description: Pitch detection plugin, made for my personal project. Makes use of platform channels (currently Android only) in order to process audio in real-time and give feedback..
version: 1.0.1
homepage: https://github.com/slins-23/flutter-fft
repository: https://github.com/slins-23/flutter-fft
environment:
    sdk: ">=2.2.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.slins.flutterfft
    pluginClass: FlutterFftPlugin
